export const ui = {
  es: {
    'title': 'Lisandro Sandoval, Mi Portfolio',
    'nav.home': 'home',
    'nav.about': 'sobre mí',
    'nav.skills': 'habilidades',
    'nav.projects': 'proyectos',
    'nav.contact': 'contacto',
    'hero.title': 'Lisandro Sandoval',
    'hero.full_subtitle': 'Estudiante de <span class="text-violet-500">Ingeniería en Sistemas de Información</span> <br/> Desarrollador Fullstack en formación',
    'info.p1': 'Soy <span class="dark:text-slate-50 text-(--midnight-blue)">estudiante de cuarto año de la carrera de Ingeniería en Sistemas de Información</span> de la UTN FRSF, con interés en entender cómo funcionan las cosas por dentro y en construir soluciones bien pensadas.',
    'info.p2': 'Trabajo principalmente con desarrollo backend y <span class="dark:text-slate-50 text-(--midnight-blue)">fullstack</span>. He desarrollado proyectos usando Node.js, TypeScript, PostgreSQL, Prisma y tecnologías web modernas, enfocándome en la lógica del negocio, manejo de datos y buenas prácticas de diseño.',
    'info.p3': 'Actualmente  <span class="dark:text-slate-50 text-(--midnight-blue)"> busco seguir aprendiendo a través de proyectos reales y dar mis primeros pasos en el mundo profesional del desarrollo de software </span>, aportando compromiso, ganas de aprender y una base técnica sólida.',
    'skills.title': 'Habilidades',
    'more.info': 'Más información',
    'skills.green': 'Dominio',
    'skills.orange': 'Familiarizado',
    'skills.yellow': 'Básico',
    'projects.title': 'Proyectos',
    'projects.pos.title': 'Sistema de Punto de Venta',
    'projects.pos.description': 'Aplicación web de punto de venta, que permite gestionar productos, ventas e inventario de manera eficiente para el comercio.',
    'projects.hotel.title': 'Sistema de Gestión Hotelera',
    'projects.hotel.description': 'Aplicación web para la gestión integral de un hotel, incluyendo reservas, habitaciones, clientes y facturación, optimizando las operaciones diarias del establecimiento.',
    'contact.title': 'Contacto',
    'contact.message': 'Mensaje',
    'contact.button': 'Enviar',
    'contact.message.example': 'Escriba su mensaje aquí...',
    'contact.email.placeholder': 'correo@ejemplo.com',
    'contact.name': 'Nombre',
    'contact.name.placeholder': 'Tu nombre',
    'contact.sending': 'Enviando...',
    'contact.success': '¡Mensaje enviado correctamente!',
    'contact.error': 'Error al enviar. Intenta nuevamente.'
  },
  en: {
    'title': 'Lisandro Sandoval, My Portfolio',
    'nav.home': 'home',
    'nav.skills': 'skills',
    'nav.about': 'about me',
    'nav.projects': 'projects',
    'nav.contact': 'contact',
    'hero.title': 'Lisandro Sandoval',
    'hero.full_subtitle': '<span class="text-violet-500">Information Systems Engineering</span> Student <br/> Fullstack Developer in training',
    'info.p1': 'I am a <span class="dark:text-slate-50 text-(--midnight-blue)">fourth-year student of Information Systems Engineering</span> at UTN FRSF, interested in understanding how things work internally and in building well-thought-out solutions.',
    'info.p2': 'I mainly work with backend and  <span class="dark:text-slate-50 text-(--midnight-blue)"> fullstack development </span>. I have developed projects using Node.js, TypeScript, PostgreSQL, Prisma, and modern web technologies, focusing on business logic, data management, and good design practices.',
    'info.p3': 'I am currently looking to  <span class="dark:text-slate-50 text-(--midnight-blue)"> continue learning through real projects and take my first steps in the professional world of software development </span>, bringing commitment, eagerness to learn, and a solid technical foundation.',
    'skills.title': 'Skills',
    'more.info': 'More information',
    'skills.green': 'Proficient',
    'skills.orange': 'Familiar',
    'skills.yellow': 'Basic',
    'projects.title': 'Projects',
    'projects.pos.title': 'Point of Sale System',
    'projects.pos.description': 'Web-based point of sale application that allows efficient management of products, sales, and inventory for the business.',
    'projects.hotel.title': 'Hotel Management System',
    'projects.hotel.description': 'Web application for comprehensive hotel management, including reservations, rooms, clients, and billing, optimizing the daily operations of the establishment.',
    'contact.title': 'Contact',
    'contact.message': 'Message',
    'contact.button': 'Send',
    'contact.message.example': 'Write your message here...',
    'contact.email.placeholder': 'email@example.com',
    'contact.name': 'Name',
    'contact.name.placeholder': 'Your name',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent successfully!',
    'contact.error': 'Error sending message. Please try again.'
  },
}

export const defaultLang = 'es';